In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
cp=pd.read_csv('cp.csv')
cp.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

### the columns are:-
1.n-nitrogen
2.p-phosphouras
3.k-potassium
4.temp=temperature
5.humidity
6.ph
7.rainfall
8.label

In [4]:
#checking of the data
cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [5]:
cp.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
cp.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [7]:
X=cp[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]
y=cp['label']

In [8]:
pd.pivot_table(cp,index=['label'],values=['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'])

,K,N,P,humidity,ph,rainfall,temperature
label,,,,,,,
apple,199.89,20.80,134.22,92.333383,5.929663,112.654779,22.630942
banana,50.05,100.23,82.01,80.358123,5.983893,104.626980,27.376798
blackgram,19.24,40.02,67.47,65.118426,7.133952,67.884151,29.973340
chickpea,79.92,40.09,67.79,16.860439,7.336957,80.058977,18.872847
coconut,30.59,21.98,16.93,94.844272,5.976562,175.686646,27.409892
coffee,29.94,101.20,28.74,58.869846,6.790308,158.066295,25.540477
cotton,19.56,117.77,46.24,79.843474,6.912675,80.398043,23.988958
grapes,200.11,23.18,132.53,81.875228,6.025937,69.611829,23.849575
jute,39.99,78.40,46.86,79.639864,6.732778,174.792798,24.958376
kidneybeans,20.05,20.75,67.54,21.605357,5.749411,105.919778,20.115085
lentil,19.41,18.77,68.36,64.804785,6.927932,45.680454,24.509052
maize,19.79,77.76,48.44,65.092249,6.245190,84.766988,22.389204
mango,29.92,20.07,27.18,50.156573,5.766373,94.704515,31.208770
mothbeans,20.23,21.44,48.01,53.160418,6.831174,51.198487,28.194920
mungbean,19.87,20.99,47.28,85.499975,6.723957,48.403601,28.525775
muskmelon,50.08,100.32,17.72,92.342802,6.358805,24.689952,28.663066
orange,10.01,19.58,16.55,92.170209,7.016957,110.474969,22.765725
papaya,50.04,49.88,59.05,92.403388,6.741442,142.627839,33.723859
pigeonpeas,20.29,20.73,67.73,48.061633,5.794175,149.457564,27.741762
pomegranate,40.21,18.87,18.75,90.125504,6.429172,107.528442,21.837842
rice,39.87,79.89,47.58,82.272822,6.425471,236.181114,23.689332
watermelon,50.22,99.42,17.00,85.160375,6.495778,50.786219,25.591767

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report

In [12]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((1760, 7), (440, 7), (1760,), (440,))

In [19]:
import warnings
warnings.filterwarnings('ignore')
log_reg=LogisticRegression()

In [20]:
log_reg.fit(X_train,Y_train)

LogisticRegression()

In [21]:
print(pd.__version__)

2.0.3

In [22]:
y_pred=log_reg.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
print(accuracy_score(Y_test,y_pred)*100)

94.54545454545455

In [25]:
X.iloc[::50]

        N    P    K  temperature   humidity        ph    rainfall
0      90   42   43    20.879744  82.002744  6.502985  202.935536
50     60   36   43    23.431219  83.063101  5.286204  219.904835
100    71   54   16    22.613600  63.690706  5.749914   87.759539
150    99   36   20    20.579819  65.345839  6.671086   78.346045
200    40   72   77    17.024985  16.988612  7.485996   88.551231
250    43   79   79    19.407517  18.980305  7.806748   80.250646
300    13   60   25    17.136928  20.595417  5.685972  128.256862
350    11   72   20    19.522262  24.926072  5.951177  113.334026
400     3   72   24    36.512684  57.928872  6.031608  122.653969
450     1   66   23    19.543172  56.928314  4.803564  173.168657
500     3   49   18    27.910952  64.709306  3.692864   32.678919
550     3   58   21    25.361405  46.826528  9.160692   55.605232
600    19   55   20    27.433294  87.805077  7.185301   54.733676
650    36   43   21    28.363194  84.859361  7.140438   52.930311
700    56   79   15    29.484400  63.199153  7.454532   71.890907
750    26   67   16    29.107131  67.905774  7.176208   67.833459
800    32   76   15    28.051536  63.498022  7.604110   43.357954
850    13   74   25    24.121926  61.095335  6.461619   44.236293
900     2   24   38    24.559816  91.635362  5.922936  111.968462
950    21    6   41    24.882445  89.396862  7.086948  107.195171
1000   91   94   46    29.367924  76.249001  6.149934   92.828409
1050  107   72   45    28.149389  81.544489  5.790768   91.405084
1100    2   40   27    29.737700  47.548852  5.954627   90.095869
1150   37   36   26    32.893002  52.613240  4.650536   94.491614
1200   24  130  195    29.996772  81.541566  6.112306   67.125345
1250   32  120  204    10.380048  83.445181  6.138959   67.391738
1300  119   25   51    26.473302  80.922544  6.283818   53.657426
1350   97   25   50    26.220060  80.901270  6.093815   49.085539
1400  115   17   55    27.578269  94.118782  6.776533   28.082532
1450  113   20   48    27.465836  94.876790  6.440585   27.278998
1500   24  128  196    22.750888  90.694892  5.521467  110.431786
1550   10  125  196    22.312537  90.035771  5.730557  113.068815
1600   22   30   12    15.781442  92.510777  6.354007  119.035002
1650   29   11    5    23.133388  91.946703  7.639788  104.422415
1700   61   68   50    35.214628  91.497251  6.793245  243.074507
1750   37   52   47    43.080227  93.903057  6.542777  211.852906
1800   18   30   29    26.762749  92.860569  6.420019  224.590366
1850   14   23   25    26.185524  96.966379  5.612123  135.418622
1900  133   47   24    24.402289  79.197320  7.231325   90.802236
1950  140   40   17    22.727672  77.075981  6.006086   77.551763
2000   89   47   38    25.524690  72.248508  6.002525  151.886997
2050   75   56   44    25.274634  73.745958  6.109478  168.043228
2100   91   21   26    26.333780  57.364700  7.261314  191.654941
2150  103   33   25    27.102104  55.749733  6.911066  139.501317

In [28]:
log_reg.predict([[99,36,20,20.579819,65.345839,6.671086,78.346045]])

array(['cotton'], dtype=object)

In [30]:
y.iloc[150]

'maize'

In [31]:
cp.iloc[2000]

N                      89
P                      47
K                      38
temperature      25.52469
humidity        72.248508
ph               6.002525
rainfall       151.886997
label                jute
Name: 2000, dtype: object

In [33]:
log_reg.predict([[89,47,38,25.52469,72.248508,6.002525,151.886997]])

array(['jute'], dtype=object)

In [ ]:
import pickle

# Replace this with your actual model variable name
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)